name: Pull Requests

on:
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint files
        run: npm run lint
      - name: Run Tests
        run: npm run test
      - uses: codecov/codecov-action@v3
